name: causica
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - jupyter_client=8.6.1
  - jupyter_core=5.5.0
  # - ld_impl_linux-64=2.38
  - libffi=3.4.4
  # - libgcc-ng=13.2.0
  - libgomp=13.2.0
  # - libnsl=2.0.0
  - libsodium=1.0.18
  # - libstdcxx-ng=11.2.0
  # - libuuid=2.38.1
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  # - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.2.1
  - packaging=24.0
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.10.1
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=25.1.2
  # - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - causal-learn==0.1.3.8
      - cdt==0.6.0
      - dataclasses-json==0.6.4
      - econml==0.15.0
      - gputil==1.4.0
      - lightgbm==4.3.0
      - lightning-utilities==0.11.2
      - marshmallow==3.21.1
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - pydeprecate==0.3.1
      - pytorch-lightning==2.2.2
      - shap==0.43.0
      - skrebate==0.62
      - slicer==0.0.7
      - sparse==0.15.1
      # - tensordict==0.3.1
      - torch==1.13.0
      - torchmetrics==0.7.0
      - typing-inspect==0.9.0
      - tensordict
      - mlflow
