name: cdml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  # - _openmp_mutex=4.5
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - ca-certificates=2024.3.11
  - comm=0.2.2
  - cycler=0.10.0
  - debugpy=1.6.7
  - decorator=4.4.2
  - dill=0.3.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.12.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=5.7.2
  - kiwisolver=1.3.1
  - lcms2=2.12
  # - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  # - libgcc-ng=13.2.0
  # - libgfortran-ng=7.5.0
  # - libgfortran4=7.5.0
  - libgomp=13.2.0
  - libpng=1.6.39
  - libsodium=1.0.18
  # - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.6
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  # - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=2.4
  - olefile=0.46
  - openssl=3.2.1
  - packaging=24.0
  - pandas=1.0.5
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=2.4.7
  - python=3.8.19
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pyzmq=25.1.2
  # - readline=8.2
  - scipy=1.4.1
  - setuptools=68.2.2
  - six=1.15.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - contourpy==1.1.1
      - fonttools==4.50.0
      - importlib-resources==6.4.0
      - matplotlib==3.3.0
      - numpy==1.17.5
      - zipp==3.18.1
